site_name: Peripatetika
site_url: https://peripatetika.com
theme: 
  name: material
  language: hr
  favicon: images/favicon.png
  logo: images/favicon.png
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Tamni način rada
      primary: indigo
      accent: deep purple   
    # Dark mode
    - scheme: slate 
      toggle:
        icon: material/lightbulb-outline
        name: Svijetli način rada
      primary: indigo
      accent: deep purple
plugins:
  - search
  - blog:
      blog_dir: .
      archive_date_format: MM/yyyy
      archive_url_date_format: MM/yyyy
      post_url_format: "{slug}"
  - tags
  - social
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
extra_javascript:
  - javascripts/force-light-mode.js
extra_css:
  - stylesheets/extra.css

copyright: 'Copyright &copy; 2025 Peripatetika Team. Contents licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC-BY-NC-SA 4.0</a>.'
     
